stages:
  - prepare
  - audit
  - cs-fix
  - lint
  - build
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"

include:
  - project: 'intern/runner-templates'
    ref: '17.0'
    file: '/npm/install-js-dependencies.yml'
  - project: 'intern/runner-templates'
    ref: '17.0'
    file: '/npm/audit.yml'
  - project: 'intern/runner-templates'
    ref: '17.0'
    file: '/homey/validate.yml'
  - project: 'intern/runner-templates'
    ref: '17.0'
    file: '/npm/code-style-fixer.yml'
  - project: 'intern/runner-templates'
    ref: '17.0'
    file: '/homey/build.yml'
  - project: 'intern/runner-templates'
    ref: '17.0'
    file: '/homey/publish.yml'
