blank_issues_enabled: false
contact_links:
  - name: â” Are you in need of support?
    url: https://homey.app/a/com.tuya2
    about: You can find our support contact e-mail address on the Homey Store page!
  - name: ğŸ’¬ Want to discuss with others?
    url: https://community.homey.app/t/146735
    about: You can use the Homey Community forum for this purpose!
